name: Build and Deploy Worker

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest' # 指定一个具体的版本号

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          mkdir -p dist
          npx wrangler deploy src/worker.js --name bpb-worker-panel --compatibility-flag [nodejs_compat] --compatibility-date "2024-11-27" --dry-run --outdir=dist
          npx javascript-obfuscator dist/worker.js --output dist/workers.js

      - name: Check if workers.js exists
        run: |
          if [ ! -f dist/workers.js ]; then
            echo "workers.js not found"
            exit 1
          fi

      - name: Create Tag    
        id: create_tag
        run: |
          tagName="v$(date +%Y%m%d%H%M%S)"
          echo "Created tag: $tagName"
          echo "::set-output name=TAG_NAME::$tagName"

      - name: Push Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "${{ steps.create_tag.outputs.TAG_NAME }}"
          git push origin "${{ steps.create_tag.outputs.TAG_NAME }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/workers.js
          asset_name: workers.js
          asset_content_type: application/javascript
          
